language: java
sudo: false # faster builds

jdk:
    - oraclejdk10
    - oraclejdk9
    - oraclejdk8

script: "mvn clean package"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 89f70bf5-4d6b-4759-8da0-dfab7881fd3e
